server:
  port: 8010
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true     # Show the queries which are executed.
  sql:
    init:
      mode: always  # always execute schema.sql
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Will allow us to refresh properties in runtime
                     # With this we can use actuator/refresh endpoint with POST method.So we can refresh.
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true # enable environment info related information
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "accounts"
    description: "Bank accounts application"
    version: "1.0.0"

logging:
  level:
    com:
      cnsn:
        accounts: DEBUG